### ISSUE TITLE
Rule prep_taxonomy fails in 1.4.5

### ISSUE THREAD

**Issue by gregdenay** [CVUA-RRW/FooDMe#42]
rule `prep_taxonomy` fails for `taxid_filter` value `None`

taxonomy_prep.log:
```
Traceback (most recent call last):
  File "/home/warmann/foodme/FooDMe/.snakemake/scripts/tmpck1f1v1d.filter_taxonomy.py", line 23, in <module>
    main(snakemake.params['nodes'],
  File "/home/warmann/foodme/FooDMe/.snakemake/scripts/tmpck1f1v1d.filter_taxonomy.py", line 18, in main
    tax.prune(taxid)
  File "/home/warmann/foodme/FooDMe/.snakemake/conda/e5bea28993829f6373b74c29065f59fe/lib/python3.10/site-packages/taxidTools/Taxonomy.py", line 600, in prune
    nodes = self.getAncestry(taxid)
  File "/home/warmann/foodme/FooDMe/.snakemake/conda/e5bea28993829f6373b74c29065f59fe/lib/python3.10/site-packages/taxidTools/Taxonomy.py", line 313, in getAncestry
    return Lineage(self[str(taxid)])
  File "/home/warmann/foodme/FooDMe/.snakemake/conda/e5bea28993829f6373b74c29065f59fe/lib/python3.10/collections/__init__.py", line 1106, in __getitem__
    raise KeyError(key)
KeyError: 'None'
```

**Comment by gregdenay** [comment]
Rule `get_taxid_from_db` fails for `taxid_filter` value `0`

```
Error in rule get_taxid_from_db:
    jobid: 17
    output: common/taxid_list.txt
    log: logs/common/taxid_form_db.log (check log file(s) for error message)
    conda-env: /home/warmann/foodme/FooDMe/.snakemake/conda/9acb6bf34844d4abfb240b4d1b416075
    shell:
        
        exec 2> logs/common/taxid_form_db.log

        export BLASTDB=/home/warmann/ncbi_nt_20220504

        blastdbcmd -db /home/warmann/ncbi_nt_20220504/nt -tax_info -outfmt %T         > common/taxid_list.txt
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job get_taxid_from_db since they might be corrupted:
common/taxid_list.txt
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
```
